### ISSUE TITLE
missing coreLibraryDesugaring configuration

### ISSUE THREAD

**Issue by Vish88781** [jayeshpansheriya/flutter_native_contact_picker#12]
when i build my it through below  error logs even 
  coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
already exit in app--build.gradle file

Launching lib\main.dart on vivo Y95 in debug mode...
Running Gradle task 'assembleDebug'...
[flutter_background_geolocation] Purging debug resources in release build

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > Could not create task ':flutter_native_contact_picker:generateDebugLintModel'.
      > coreLibraryDesugaring configuration contains no dependencies. If you intend to enable core library desugaring, please add dependencies to coreLibraryDesugaring configuration.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 9s

**Comment by jayeshpansheriya** [comment]
@Vish88781  please share more details, flutter and android version.
