### ISSUE TITLE
error coming on latest sdk dependancies

### ISSUE THREAD

**Issue by vikasyadav2184** [jayeshpansheriya/flutter_native_contact_picker#15]
Caused by: java.lang.RuntimeException: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.

Hello,

 I have updated my project to gradle 8.5.0 and and using your plugin in our project.
lastest flutter version and dart version.
andorid sdk 34-35. 

Please update the version for latest releases.
Thank you.

**Comment by jayeshpansheriya** [comment]
@vikasyadav2184  please check with git url.

**Comment by vikasyadav2184** [comment]
Hello,
can you confirm when you release the new version on "flutter package" of this.

**Comment by khaled-0** [comment]
@vikasyadav2184 hi, im getting new error on git 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_native_contact_picker:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/home/khaled/Workspace/AMRServer/Flutter-UserClient/build/flutter_native_contact_picker/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.

**Comment by jayeshpansheriya** [comment]
@vikasyadav2184  @khaled-0  try to use prerelease version.

**Comment by jayeshpansheriya** [comment]
Duplicate #17
