### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by erperejildo** [jayeshpansheriya/flutter_native_contact_picker#16]
I just moved from `flutter_contact_picker` package and I'm missing multiple properties:

![image](https://github.com/user-attachments/assets/d02f7c2b-c4d3-4292-9a76-b06cbe8293c9)

**Comment by jayeshpansheriya** [comment]
@erperejildo Please share more detail
flutter version, plugin version, and error.

**Comment by erperejildo** [comment]
I'm no longer using this package
