### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by ashutosh-mulik** [jayeshpansheriya/flutter_native_contact_picker#3]
Unhandled Exception: MissingPluginException(No implementation found for method selectContact on channel flutter_native_contact_picker)

**Comment by ashutosh-mulik** [comment]
Solution :
Flutter clean build.

**Comment by jayeshpansheriya** [comment]
> Solution : Flutter clean build.

thanks for sharing solution.

**Comment by yeabsera-w** [comment]
> Solution : Flutter clean build.

but this is not working for me
